### ISSUE TITLE
Trouble with plugins DSL

### ISSUE THREAD

**Issue by kylannjohnson** [dorongold/gradle-task-tree#10]
I'm having trouble using the plugin as you've specified.  I'm on Gradle 3.3, but our project doesn't use the Plugins block described here: https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block

Is there another way to apply the plugin?

Using the `plugins` syntax results in this error:  "only buildscript {} and other plugins {} script blocks are allowed before plugins {} blocks"

However, moving the block has no effect.

Regardless, this visualizer looks good and would be a great help

**Comment by dorongold** [comment]
Hi,

You don't have to use the Plugin block.
Instead you can apply the plugin the traditional way (should be similar to how you apply plugins today):

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.dorongold.plugins:task-tree:1.2.2"
  }
}

apply plugin: "com.dorongold.task-tree"
```

This snippet is copied from here:
https://plugins.gradle.org/plugin/com.dorongold.task-tree
