### ISSUE TITLE
cant find the plugin in repo

### ISSUE THREAD

**Issue by amit-handa** [dorongold/gradle-task-tree#15]
It doesnt list the jar:
https://plugins.gradle.org/m2/gradle/plugin/com/dorongold/task-tree/1.3/task-tree-1.3.jar redirects to ->
https://repo.jfrog.org/artifactory/libs-release-bintray/gradle/plugin/com/dorongold/task-tree/1.3/task-tree-1.3.jar?referrer

gradle version: 4.0

build.gradle.kts
==================
apply {
    plugin("com.dorongold.task-tree")
}

buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            setUrl("https://plugins.gradle.org/m2/")
        }
    }
    dependencies {
        classpath("gradle.plugin.com.dorongold:task-tree:1.3")
    }
}
-----------------------------

What am I missing ?

**Comment by dorongold** [comment]
The correct build script snippet is:
```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.dorongold.plugins:task-tree:1.3"
  }
}

apply plugin: "com.dorongold.task-tree"
```

You seem to have a mistake in this line: `classpath("gradle.plugin.com.dorongold:task-tree:1.3")`
Please fix it to: `classpath("gradle.plugin.com.dorongold.plugins:task-tree:1.3")`
