### ISSUE TITLE
Surface Java and Gradle versions required

### ISSUE THREAD

**Issue by ncalexan** [dorongold/gradle-task-tree#2]
It would help to document the requirements clearly, because both tripped me up.  You need to use Java 1.8 (by default, I use 1.7); and you need to use a Gradle more recent than 2.2.1 to avoid

```
> Could not find method getClientMetaData() for arguments [] on task ':taskTree'.
```

(I've had success with Gradle 2.7, but I haven't bisected for when the relevant method was added to Gradle.)

Thanks for this tool -- I appreciate it greatly.  Much easier to use than the GraphViz solution you based this work on.

**Comment by dorongold** [comment]
I checked and found out that the method `getClientMetaData()` was added in Gradle version 2.3.
Also, I rebuilt the plugin with `sourceCompatibility = 1.7`. I published the the new plugin build as version 1.0.1.
So the plugin should now work with Gradle version 2.3+ and Java version 1.7+.

I added a Version Compatibility section to the README.

Thank you for drawing my attention to these issues.

I'm glad you find the plugin useful!
