### ISSUE TITLE
Use official API Option class instead of deprecated internal one

### ISSUE THREAD

**Issue by mkordas** [dorongold/gradle-task-tree#22]
Plugin uses deprecated `org.gradle.api.internal.tasks.options.Option`, but it has corresponding API class `org.gradle.api.tasks.options.Option`.

**Comment by jhansche** [comment]
Looks like this was resolved with e06e5642cdf9f1d1854a0cf06cba3cf821afebb6
@dorongold

**Comment by mkordas** [comment]
@jhansche thanks!
