### ISSUE TITLE
Missing Git tag for 1.3.1

### ISSUE THREAD

**Issue by szpak** [dorongold/gradle-task-tree#25]
There tag for 1.3.1 has [not](https://github.com/dorongold/gradle-task-tree/releases) be created (or most likely pushed to GitHub). Therefore, people cannot be sure from which Git tag it was built and (probably more importantly) all people who starred the project (and enabled notifications about the new releases) hasn't been informed about that (I was surprised trying to use the plugin with just released Gradle 5.0-rc-1).

**Comment by dorongold** [comment]
Thanks for the heads-up.
I have just created a new tag (and release) for 1.3.1.
