### ISSUE TITLE
Error creating singleton class when using taskTree plugin 

### ISSUE THREAD

**Issue by kobi26c** [dorongold/gradle-task-tree#26]
Hi, 
I'm facing the following issue when using task tree plugin: 

I'm trying to create a singleton instance under a buildSrc code.
When I apply the task tree plugin - the Instance is created twice, When I comment the apply - it created only once. 

Ways to reproduce: 
1. Create the following file hierarchy:  
![image](https://user-images.githubusercontent.com/10359526/49144815-f0329400-f306-11e8-9d4a-00f083adf4cf.png) 
buildSrc settings.gradle:
`rootProject.name = 'test-plugin'`

buildSrc build.gradle:
```
plugins {
    id 'groovy'
    id 'java-gradle-plugin'
}

group 'com.amat.gradle'
version '1.0'`

```
DependencyManager.groovy: 

```
class DependencyManager {


    private static DependencyManager INSTANCE = null

    static DependencyManager getInstance() {
        if(Objects.isNull(INSTANCE)) {
            INSTANCE = new DependencyManager()
            println "INSTACE CREATED"
        }

        return INSTANCE
    }

    private DependencyManager() {

    }

    void callMe() {}


}
```

Main module: 
settings.gradle: 

```

includeBuild "../plugins/gradle/buildSrc"
//unfortunately, this does not remove the need to define the plugins using pluginManagement to be able to use them in plugins{} blocks
gradle.addProjectEvaluationListener(new ProjectEvaluationListener() {
    @Override
    void beforeEvaluate(Project project) {
        //things added to root project are also available to subprojects
        if (project.rootProject == project) {
            project.buildscript.dependencies.add("classpath", "com.amat.gradle:test-plugin:1.0")
        }
    }

    @Override
    void afterEvaluate(Project project, ProjectState state) { }
})

```

build.gradle:
```

import com.DependencyManager

plugins {

    id "base" // for 'clean' and clean rules
    //Optional - help to debug tasks dependencies !!!
    // wil be available also to sub projects
    id "com.dorongold.task-tree" version "1.3.1"
    id "project-report"
}


apply from: "../plugins/gradle/Test/sample.gradle"

DependencyManager.getInstance().callMe()


```
Output with applying task tree: 
![image](https://user-images.githubusercontent.com/10359526/49144994-6afbaf00-f307-11e8-8fb7-f99847dccebb.png)

Output when commenting task tree plugin: 
![image](https://user-images.githubusercontent.com/10359526/49145025-7b138e80-f307-11e8-8136-ff2f9f11c70c.png)

Any way you can help me figure out if this is a bug or something that I can fix ?

Thanks

**Comment by dorongold** [comment]
Closing this issue because it's stale.
