### ISSUE TITLE
Nothing is printed for single project

### ISSUE THREAD

**Issue by jvmlet** [dorongold/gradle-task-tree#44]
I have single flat project  (without subprojects)

I execute `gradlew build taskTree --init-script $pathToScriptBelow`

```
initscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2" }
    }
    dependencies {
        classpath "gradle.plugin.com.dorongold.plugins:task-tree:1.5"
    }
}
rootProject {
    apply plugin: com.dorongold.gradle.tasktree.TaskTreePlugin
}
```
and nothing is printed.

**Comment by dorongold** [comment]
Fixed by fb19b847e2a6c419092c2231cc1839377bfb675b.

**Comment by jvmlet** [comment]
Thanks, `gradle-task-tree` was integrated into IntelliJ IDEA [plugin](https://plugins.jetbrains.com/plugin/11236-reveal-gradle-dependency-in-external-libraries-tree-)

**Comment by dorongold** [comment]
@jvmlet That's awesome!
Also, thanks for the credits in your README and plugin description.

I now added a reference to your plugin here in the README.
d11352e30b755b257f30a6dc10d2369236cb4ba0
