### ISSUE TITLE
2.1.1 doesn't work with the configuration cache

### ISSUE THREAD

**Issue by nikclayton** [dorongold/gradle-task-tree#52]
Using v2.1.1 with the configuration cache enabled fails with an exception.

https://scans.gradle.com/s/bwxvaieqlwmsm is the result after running `./gradlew build taskTree --scan`. I couldn't see anything helpful in there.

Running it without the configuration cache, `./gradlew build taskTree --no-configuration-cache`, works as expected

**Comment by dorongold** [comment]
Fixed by https://github.com/dorongold/gradle-task-tree/pull/56 with plugin version 4.0.0.
