### ISSUE TITLE
Gradle 8

### ISSUE THREAD

**Issue by jvmlet** [dorongold/gradle-task-tree#53]
@dorongold , people are complaining
https://github.com/jvmlet/reveal-dependency-plugin/issues/2

**Comment by jvmlet** [comment]
@dorongold , saw this Gradle 9.1.0 Release Notes https://share.google/VRFtp5DYIFs9P3LTt??

**Comment by dorongold** [comment]
@jvmlet I saw it now. Thanks for bringing this to my attention.
I'm happy that finally Gradle is implementing this feature, 10 years after my [original question](https://discuss.gradle.org/t/how-to-print-task-graph/11509) 🙂.

gradle/gradle#34298 also closes this long standing issue: gradle/gradle#980
