### ISSUE TITLE
Execution failed on Gradle 2.14

### ISSUE THREAD

**Issue by olaf-a** [dorongold/gradle-task-tree#6]
When I run the tool using Gradle 2.8 it all works fine, when running Gradle 2.14 I get:

```
:taskTree FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':taskTree'.
> Cannot cast object 'org.gradle.internal.logging.services.LoggingBackedStyledTextOutput@14ace6a8' with class 'org.gradle.internal.logging.services.LoggingBackedStyledTextOutput' to class 'org.gradle.logging.StyledTextOutput'


```

**Comment by dorongold** [comment]
Thanks for reporting this.
In gradle version 2.14 an internal gradle class used by this plugin was deprecated and moved to a different package.
I committed a fix: ea4a058ff239bd497e73d66b06a224c78c2ccd1d.
I also published to gradle plugin portal a new version of Task Tree Plugin: **1.2.2**.
Version 1.2.2 of the plugin will only work with gradle versions 2.14+.
Version 1.2.1 of the plugin must be used for gradle vresions 2.3-2.13.
